import type { GeneratedFile } from "@/agents/build/base-build.agent";

export async function createGitHubRepo(
  token: string,
  appName: string,
  files: GeneratedFile[]
): Promise<string> {
  const slug = appName.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  // Create the repo
  const createRes = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers,
    body: JSON.stringify({
      name: slug,
      description: `Generated by LaunchForge AI`,
      private: true,
      auto_init: false,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json();
    throw new Error(`GitHub repo creation failed: ${err.message}`);
  }

  const repo = await createRes.json();
  const repoFullName = repo.full_name;

  // Push files via Git Data API — create a tree and commit
  const fileTree = await Promise.all(
    files.map(async (file) => ({
      path: file.path,
      mode: "100644" as const,
      type: "blob" as const,
      content: file.content,
    }))
  );

  // Create tree
  const treeRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/trees`, {
    method: "POST",
    headers,
    body: JSON.stringify({ tree: fileTree }),
  });
  const tree = await treeRes.json();

  // Create commit
  const commitRes = await fetch(`https://api.github.com/repos/${repoFullName}/git/commits`, {
    method: "POST",
    headers,
    body: JSON.stringify({
      message: "Initial commit: generated by LaunchForge AI",
      tree: tree.sha,
      parents: [],
    }),
  });
  const commit = await commitRes.json();

  // Set HEAD to main branch
  await fetch(`https://api.github.com/repos/${repoFullName}/git/refs`, {
    method: "POST",
    headers,
    body: JSON.stringify({ ref: "refs/heads/main", sha: commit.sha }),
  });

  return repo.html_url as string;
}
